### ISSUE TITLE
Question.

### ISSUE THREAD

**Issue by juliolitwin** [wobes1/Equilibrium.NET#1]
Yo,

Will there still be an update on the project? Since a few months ago and there is no more update and without the source code.

It would be wonderful to be able to learn directly from your own project and it will open a vast door of knowledge for other interested people.

Cheers.

**Comment by wobes1** [comment]
Hi there @juliolitwin thanks for getting in touch,

I regret to inform that there was no much of work done for the past months due lack of time / unsuitability due to constant Unity ECS API changes. However, I am happy to announce that I resumed the work not so long ago and working on updating the code on the latest API (ex. SystemBase, IJobForeach lambda). While majority of the jobified code is still in IJobChunk I found couple spots where I could improve priority and AOI calculation for the project. here is the [forum post](https://forum.unity.com/threads/showcase-enet-unity-ecs-5000-real-time-player-simulation.605656/) that uses somehow outdated approach but still good for start. I would say the work is 70% finished so stay tuned.

King regards,
Alexander.

**Comment by juliolitwin** [comment]
Thanks for answering me. 

I'm really excited about your project/library, your showcase videos are impressive. My focus is more on studying the networking (ENet -maybe-) and synchronization (time, extra, inter, pred and etc.) of how you work with them. ECS is still my distant goal.

I can't wait to see your project here on github and I was already following on the forum! :)

Cheers.

**Comment by wobes1** [comment]
@juliolitwin what I always suggest is to get your prototype running just using OOP. I use ECS just to process massive amount of data (ex. tracking changing fields, calculate priority per entity per client per replication model, calculate AOI using hashing grid etc.). Later on all that needs to be tightly packed / sent from a server to its clients. 

Extrapolation, interpolation, prediction are more visual smoothing topics to make your project(s) playable. Networking is all about proper simulation and proper state replication. ENet is good as a transport library (afaik Photon still uses it) . I can't speak of what is your current progress but I can definitely suggest articles / talks if you would need them.

**Comment by wobes1** [comment]
@juliolitwin ah, and thank you for your kind words. I am flattered.

**Comment by juliolitwin** [comment]
I will be grateful for the help with the articles! My current knowledge with these techniques is still very early, I am seeing some projects to understand a little better, but sometimes the techniques themselves are not applied as correctly or not completed.

My question is also that I see some differences in techniques and discussions to synchronize the server clock with the client, so I end up feeling a tightrope, since I believe that clock synchronization is one of the main parts for the other techniques. I worry about the performance and bandwidth of having to send several times a second to synchronize.

Regards.
